# These are supported funding model platforms

patreon: simulatorcontroller
custom: https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/donate?hosted_button_id=7GV86ZPS95SL6
